# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:


trigger:
- master

  
pool:
  #vmImage: 'ubuntu-latest'
  vmImage: 'ubuntu-16.04'

steps:
- script: echo MULTIPLE JOBS SEQUENTIAL!!!!!
  displayName: 'Job1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/shell
  displayName: 'Job2'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/shell
  displayName: 'Job3'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/shell
  displayName: 'Job2'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/shell
  displayName: 'Job3'
